
server.port=8080
spring.application.name=smartretail-backend

spring.data.mongodb.uri=mongodb+srv://priyanka_sharma0516:ByyEQik5bDAaUp4U@cluster0.azjhv2j.mongodb.net/smartretail_db?retryWrites=true&w=majority


app.jwt.secret=SmartRetailERPSecretKey2025VeryLongSecretKeyForHS512Algorithm!@#$
app.jwt.expiration=86400000


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=./uploads/


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


app.cors.allowed-origins=http://localhost:3000,http://localhost:5173


logging.level.com.smartretail=DEBUG
logging.level.org.springframework.security=WARN


spring.cache.type=simple
